#!/usr/bin/env node
import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';

import { loadConfig, getConfigTemplate } from './config';
import { YuqueClient } from './yuque-client';
import { getRepoRoot, getChangedFilesForPush, getChangedFilesSinceRemote } from './git';
import { syncChanges, printSummary } from './sync';

const program = new Command();

program
    .name('gty')
    .description('git-to-yuque: Sync local git changes to Yuque documents')
    .version('1.0.0');

// ──────────────────────────────────────────
// gty init
// ──────────────────────────────────────────
program
    .command('init')
    .description('Generate a .gty.yml config file template in the current directory')
    .option('-f, --force', 'Overwrite existing .gty.yml', false)
    .action((opts: { force: boolean }) => {
        const dest = path.join(process.cwd(), '.gty.yml');
        if (fs.existsSync(dest) && !opts.force) {
            console.error(chalk.yellow(`⚠  .gty.yml already exists. Use --force to overwrite.`));
            process.exit(1);
        }
        fs.writeFileSync(dest, getConfigTemplate(), 'utf8');
        console.log(chalk.green(`✅ Created .gty.yml at ${dest}`));
        console.log(chalk.gray(`   Edit it to set your token and namespace, then run "gty install".`));
    });

// ──────────────────────────────────────────
// gty install
// ──────────────────────────────────────────
program
    .command('install')
    .description('Install the git pre-push hook in the current repository')
    .option('--force', 'Overwrite existing pre-push hook', false)
    .action((opts: { force: boolean }) => {
        const repoRoot = getRepoRoot();
        const hooksDir = path.join(repoRoot, '.git', 'hooks');
        const hookPath = path.join(hooksDir, 'pre-push');

        if (!fs.existsSync(hooksDir)) {
            console.error(chalk.red(`❌ .git/hooks directory not found at ${hooksDir}`));
            process.exit(1);
        }

        if (fs.existsSync(hookPath) && !opts.force) {
            const existing = fs.readFileSync(hookPath, 'utf8');
            if (existing.includes('git-to-yuque')) {
                console.log(chalk.yellow('ℹ  pre-push hook already installed. Use --force to reinstall.'));
                return;
            }
            // Append to existing hook
            const appended = existing.trimEnd() + '\n\n# git-to-yuque\ngty sync --remote "$1" --branch "$2"\n';
            fs.writeFileSync(hookPath, appended, { mode: 0o755 });
            console.log(chalk.green(`✅ Appended gty sync to existing pre-push hook at ${hookPath}`));
            return;
        }

        const hookContent = `#!/bin/sh
# git-to-yuque pre-push hook
# Automatically syncs markdown changes to Yuque before push.
# Generated by: gty install

remote="$1"
url="$2"

while read local_ref local_sha remote_ref remote_sha; do
  branch=$(echo "$remote_ref" | sed 's|refs/heads/||')
  gty sync --remote "$remote" --branch "$branch"
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
    echo "[git-to-yuque] Sync failed (exit $exit_code). Check continueOnError in .gty.yml."
  fi
done

exit 0
`;

        fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
        console.log(chalk.green(`✅ Installed pre-push hook at ${hookPath}`));
        console.log(chalk.gray(`   The hook will run "gty sync" automatically before each git push.`));
    });

// ──────────────────────────────────────────
// gty uninstall
// ──────────────────────────────────────────
program
    .command('uninstall')
    .description('Remove the git pre-push hook')
    .action(() => {
        const repoRoot = getRepoRoot();
        const hookPath = path.join(repoRoot, '.git', 'hooks', 'pre-push');
        if (!fs.existsSync(hookPath)) {
            console.log(chalk.gray('No pre-push hook found.'));
            return;
        }
        const content = fs.readFileSync(hookPath, 'utf8');
        if (!content.includes('git-to-yuque')) {
            console.log(chalk.gray('Hook does not contain git-to-yuque. Nothing to remove.'));
            return;
        }
        fs.unlinkSync(hookPath);
        console.log(chalk.green('✅ Removed pre-push hook.'));
    });

// ──────────────────────────────────────────
// gty check
// ──────────────────────────────────────────
program
    .command('check')
    .description('Verify config and test Yuque API connection')
    .action(async () => {
        try {
            const { config, configPath } = loadConfig();
            console.log(chalk.cyan(`📋 Config: ${configPath}`));
            console.log(chalk.cyan(`   namespace: ${config.namespace}`));
            console.log(chalk.cyan(`   baseUrl:   ${config.baseUrl}`));
            console.log(chalk.cyan(`   syncMode:  ${config.syncMode}`));
            console.log(chalk.cyan(`   syncFolders: ${config.syncFolders}`));

            const client = new YuqueClient(config);
            process.stdout.write('🔍 Connecting to Yuque... ');
            const user = await client.getCurrentUser();
            console.log(chalk.green(`OK (user: ${user.name} / ${user.login})`));

            process.stdout.write('🔍 Fetching TOC... ');
            const toc = await client.getToc();
            console.log(chalk.green(`OK (${toc.length} nodes)`));

            console.log(chalk.green('\n✅ All checks passed!'));
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            console.error(chalk.red(`\n❌ Check failed: ${msg}`));
            process.exit(1);
        }
    });

// ──────────────────────────────────────────
// gty sync
// ──────────────────────────────────────────
program
    .command('sync')
    .description('Sync changed markdown files to Yuque')
    .option('--remote <remote>', 'Remote name (used in pre-push hook context)', '')
    .option('--branch <branch>', 'Remote branch name (used in pre-push hook context)', '')
    .option('--dry-run', 'Preview what would be synced without making changes', false)
    .option('--all', 'Sync all matching files regardless of git diff', false)
    .action(async (opts: { remote: string; branch: string; dryRun: boolean; all: boolean }) => {
        try {
            const repoRoot = getRepoRoot();
            const { config } = loadConfig(repoRoot);

            if (opts.dryRun) {
                console.log(chalk.yellow('🔍 Dry-run mode: no changes will be made to Yuque.\n'));
            }

            // Determine which files changed
            let changes;
            if (opts.remote && opts.branch) {
                // Called from pre-push hook
                console.log(chalk.gray(`Getting changes for push to ${opts.remote}/${opts.branch}...`));
                changes = getChangedFilesForPush(opts.remote, opts.branch, repoRoot);
            } else if (opts.all) {
                // Sync everything: treat all markdown as "modified"
                console.log(chalk.gray('Syncing all files (--all mode)...'));
                const { execSync } = await import('child_process');
                const allFiles = execSync('git ls-files --cached', { cwd: repoRoot, encoding: 'utf8' })
                    .split('\n').filter(Boolean);
                changes = allFiles.map(p => ({ type: 'modified' as const, path: p }));
            } else {
                // Manual sync: diff against upstream
                console.log(chalk.gray('Getting changes since remote...'));
                changes = getChangedFilesSinceRemote(repoRoot);
            }

            if (changes.length === 0) {
                console.log(chalk.gray('✅ No changes to sync.'));
                return;
            }

            console.log(chalk.cyan(`\n🚀 Syncing ${changes.length} changed file(s) to Yuque...\n`));

            const results = await syncChanges({
                config,
                repoRoot,
                changes,
                dryRun: opts.dryRun,
            });

            printSummary(results);

            const hasErrors = results.some(r => r.status === 'error');
            if (hasErrors && !config.continueOnError) {
                process.exit(1);
            }
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            console.error(chalk.red(`\n❌ Sync failed: ${msg}`));

            let continueOnError = true;
            try {
                const { config } = loadConfig();
                continueOnError = config.continueOnError;
            } catch { /* ignore */ }

            if (!continueOnError) {
                process.exit(1);
            }
        }
    });

program.parse(process.argv);
