#!/usr/bin/env node
import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';

import { loadConfig, getConfigTemplate } from './config';
import { YuqueClient } from './yuque-client';
import {
    getRepoRoot, getChangedFilesForPush, getChangedFilesSinceRemote,
    getStagedMarkdownFiles, getAllTrackedMarkdownFiles,
} from './git';
import { syncChanges, printSummary } from './sync';
import { toDocSlug, isExcluded } from './mapper';
import { minimatch } from 'minimatch';

const program = new Command();

program
    .name('gty')
    .description('git-to-yuque: Sync local git changes to Yuque documents')
    .version('1.0.0');

// ──────────────────────────────────────────
// gty init
// ──────────────────────────────────────────
program
    .command('init')
    .description('Generate a .gty.yml config file template in the current directory')
    .option('-f, --force', 'Overwrite existing .gty.yml', false)
    .action((opts: { force: boolean }) => {
        const dest = path.join(process.cwd(), '.gty.yml');
        if (fs.existsSync(dest) && !opts.force) {
            console.error(chalk.yellow(`⚠  .gty.yml already exists. Use --force to overwrite.`));
            process.exit(1);
        }
        fs.writeFileSync(dest, getConfigTemplate(), 'utf8');
        console.log(chalk.green(`✅ Created .gty.yml at ${dest}`));
        console.log(chalk.gray(`   Edit it to set your token and namespace, then run "gty install".`));
    });

// ──────────────────────────────────────────
// gty install
// ──────────────────────────────────────────
program
    .command('install')
    .description('Install git pre-commit (slug check) and pre-push (sync) hooks')
    .option('--force', 'Overwrite existing hooks', false)
    .action((opts: { force: boolean }) => {
        const repoRoot = getRepoRoot();
        const hooksDir = path.join(repoRoot, '.git', 'hooks');

        if (!fs.existsSync(hooksDir)) {
            console.error(chalk.red(`❌ .git/hooks directory not found at ${hooksDir}`));
            process.exit(1);
        }

        // ── pre-commit hook (slug conflict guard) ──
        const preCommitPath = path.join(hooksDir, 'pre-commit');
        const preCommitContent = `#!/bin/sh
# git-to-yuque pre-commit hook
# Blocks commit if markdown files would produce duplicate Yuque slugs.
# Generated by: gty install
gty lint
exit $?
`;
        installHook(preCommitPath, preCommitContent, 'pre-commit', opts.force);

        // ── pre-push hook (sync) ──
        const prePushPath = path.join(hooksDir, 'pre-push');
        const prePushContent = `#!/bin/sh
# git-to-yuque pre-push hook
# Automatically syncs markdown changes to Yuque before push.
# Generated by: gty install

remote="$1"
url="$2"

while read local_ref local_sha remote_ref remote_sha; do
  branch=$(echo "$remote_ref" | sed 's|refs/heads/||')
  gty sync --remote "$remote" --branch "$branch"
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
    echo "[git-to-yuque] Sync failed (exit $exit_code). Check continueOnError in .gty.yml."
  fi
done

exit 0
`;
        installHook(prePushPath, prePushContent, 'pre-push', opts.force);
    });

function installHook(hookPath: string, content: string, name: string, force: boolean) {
    if (fs.existsSync(hookPath) && !force) {
        const existing = fs.readFileSync(hookPath, 'utf8');
        if (existing.includes('git-to-yuque')) {
            console.log(chalk.yellow(`ℹ  ${name} hook already installed.`));
            return;
        }
        // Append to an existing hook that doesn't contain our marker
        const appended = existing.trimEnd() + `\n\n# git-to-yuque\n${content.split('\n').slice(3).join('\n')}`;
        fs.writeFileSync(hookPath, appended, { mode: 0o755 });
        console.log(chalk.green(`✅ Appended to existing ${name} hook.`));
        return;
    }
    fs.writeFileSync(hookPath, content, { mode: 0o755 });
    console.log(chalk.green(`✅ Installed ${name} hook at ${hookPath}`));
}

// ──────────────────────────────────────────
// gty uninstall
// ──────────────────────────────────────────
program
    .command('uninstall')
    .description('Remove the git pre-commit and pre-push hooks')
    .action(() => {
        const repoRoot = getRepoRoot();
        const hooksDir = path.join(repoRoot, '.git', 'hooks');
        let removed = 0;
        for (const name of ['pre-commit', 'pre-push']) {
            const hookPath = path.join(hooksDir, name);
            if (!fs.existsSync(hookPath)) continue;
            const content = fs.readFileSync(hookPath, 'utf8');
            if (!content.includes('git-to-yuque')) continue;
            fs.unlinkSync(hookPath);
            console.log(chalk.green(`✅ Removed ${name} hook.`));
            removed++;
        }
        if (removed === 0) console.log(chalk.gray('No git-to-yuque hooks found.'));
    });

// ──────────────────────────────────────────
// gty lint  (pre-commit slug conflict check)
// ──────────────────────────────────────────
program
    .command('lint')
    .description('Check for markdown files that would generate duplicate Yuque slugs')
    .option('--all', 'Check all tracked files (not just staged)', false)
    .action((opts: { all: boolean }) => {
        try {
            const repoRoot = getRepoRoot();
            const { config } = loadConfig(repoRoot);

            const filterFn = (f: string) => {
                if (isExcluded(f, config.exclude)) return false;
                if (config.mappings.length === 0) return true;
                return config.mappings.some(m => minimatch(f, m.pattern, { dot: true }));
            };

            let filesToScan: string[];
            let stagedSet: Set<string>;

            if (opts.all) {
                // Full scan: check everything, no notion of "staged"
                filesToScan = getAllTrackedMarkdownFiles(repoRoot).filter(filterFn);
                stagedSet = new Set(filesToScan); // treat all as "relevant"
            } else {
                // Pre-commit context:
                // 1. Get staged files (what's about to be committed)
                // 2. Union with ALL tracked files to catch cross-commit conflicts
                // 3. Only report a conflict if a STAGED file is involved
                const staged = getStagedMarkdownFiles(repoRoot).filter(filterFn);
                const allTracked = getAllTrackedMarkdownFiles(repoRoot).filter(filterFn);
                stagedSet = new Set(staged);

                // Union: deduplicate (allTracked already includes committed versions of staged files)
                const unionSet = new Set([...allTracked, ...staged]);
                filesToScan = [...unionSet];
            }

            if (filesToScan.length === 0) {
                console.log(chalk.gray('✅ No markdown files to check.'));
                return;
            }

            // Derive slug for each file and build a slug → [files] map
            const slugToFiles = new Map<string, string[]>();
            for (const f of filesToScan) {
                const rule = config.mappings.find(m => minimatch(f, m.pattern, { dot: true }));
                const slug = toDocSlug(f, rule?.docSlug);
                const existing = slugToFiles.get(slug) ?? [];
                existing.push(f);
                slugToFiles.set(slug, existing);
            }

            // A conflict exists only when ≥2 files share a slug
            // AND at least one of those files is in the staged set (or --all mode)
            const conflicts = [...slugToFiles.entries()].filter(
                ([, group]) => group.length > 1 && group.some(f => stagedSet.has(f))
            );

            if (conflicts.length === 0) {
                const scope = opts.all ? filesToScan.length : stagedSet.size;
                console.log(chalk.green(`✅ No slug conflicts found (${scope} staged file(s) checked against ${filesToScan.length} total).`));
                return;
            }

            // Report conflicts and exit 1 to block the commit
            console.error(chalk.red(`\n❌ Slug conflicts detected! These files would overwrite each other in Yuque:\n`));
            for (const [slug, conflictFiles] of conflicts) {
                console.error(chalk.red(`  slug "${slug}":`));
                for (const f of conflictFiles) {
                    const tag = stagedSet.has(f) ? chalk.yellow(' ← staged') : chalk.gray(' (existing)');
                    console.error(chalk.red(`    - ${f}`) + tag);
                }
            }
            console.error(chalk.yellow(`\n💡 Fix: set docSlug: "{path}" in your .gty.yml mappings to use the full path as slug.`));
            process.exit(1);
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            console.error(chalk.red(`\n❌ lint failed: ${msg}`));
            process.exit(1);
        }
    });

// ──────────────────────────────────────────
// gty check
// ──────────────────────────────────────────
program
    .command('check')
    .description('Verify config and test Yuque API connection')
    .action(async () => {
        try {
            const { config, configPath } = loadConfig();
            console.log(chalk.cyan(`📋 Config: ${configPath}`));
            console.log(chalk.cyan(`   namespace: ${config.namespace}`));
            console.log(chalk.cyan(`   baseUrl:   ${config.baseUrl}`));
            console.log(chalk.cyan(`   syncMode:  ${config.syncMode}`));
            console.log(chalk.cyan(`   syncFolders: ${config.syncFolders}`));

            const client = new YuqueClient(config);
            process.stdout.write('🔍 Connecting to Yuque... ');
            const user = await client.getCurrentUser();
            console.log(chalk.green(`OK (user: ${user.name} / ${user.login})`));

            process.stdout.write('🔍 Fetching TOC... ');
            const toc = await client.getToc();
            console.log(chalk.green(`OK (${toc.length} nodes)`));

            console.log(chalk.green('\n✅ All checks passed!'));
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            console.error(chalk.red(`\n❌ Check failed: ${msg}`));
            process.exit(1);
        }
    });

// ──────────────────────────────────────────
// gty sync
// ──────────────────────────────────────────
program
    .command('sync')
    .description('Sync changed markdown files to Yuque')
    .option('--remote <remote>', 'Remote name (used in pre-push hook context)', '')
    .option('--branch <branch>', 'Remote branch name (used in pre-push hook context)', '')
    .option('--dry-run', 'Preview what would be synced without making changes', false)
    .option('--all', 'Sync all matching files regardless of git diff', false)
    .action(async (opts: { remote: string; branch: string; dryRun: boolean; all: boolean }) => {
        try {
            const repoRoot = getRepoRoot();
            const { config } = loadConfig(repoRoot);

            if (opts.dryRun) {
                console.log(chalk.yellow('🔍 Dry-run mode: no changes will be made to Yuque.\n'));
            }

            // Determine which files changed
            let changes;
            if (opts.remote && opts.branch) {
                // Called from pre-push hook
                console.log(chalk.gray(`Getting changes for push to ${opts.remote}/${opts.branch}...`));
                changes = getChangedFilesForPush(opts.remote, opts.branch, repoRoot);
            } else if (opts.all) {
                // Sync everything: treat all markdown as "modified"
                console.log(chalk.gray('Syncing all files (--all mode)...'));
                const { execSync } = await import('child_process');
                const allFiles = execSync('git ls-files --cached', { cwd: repoRoot, encoding: 'utf8' })
                    .split('\n').filter(Boolean);
                changes = allFiles.map(p => ({ type: 'modified' as const, path: p }));
            } else {
                // Manual sync: diff against upstream
                console.log(chalk.gray('Getting changes since remote...'));
                changes = getChangedFilesSinceRemote(repoRoot);
            }

            if (changes.length === 0) {
                console.log(chalk.gray('✅ No changes to sync.'));
                return;
            }

            console.log(chalk.cyan(`\n🚀 Syncing ${changes.length} changed file(s) to Yuque...\n`));

            const results = await syncChanges({
                config,
                repoRoot,
                changes,
                dryRun: opts.dryRun,
            });

            printSummary(results);

            const hasErrors = results.some(r => r.status === 'error');
            if (hasErrors && !config.continueOnError) {
                process.exit(1);
            }
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            console.error(chalk.red(`\n❌ Sync failed: ${msg}`));

            let continueOnError = true;
            try {
                const { config } = loadConfig();
                continueOnError = config.continueOnError;
            } catch { /* ignore */ }

            if (!continueOnError) {
                process.exit(1);
            }
        }
    });

program.parse(process.argv);
